# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@title Function to create a factor
#'
#'@description Function creates a factor when supplied with a numeric vector and character vector for levels
#'
#'@param x a numeric vector that denotes the indexes of the factor
#'@param levels character vector for the unique levels of the factor
#'@return a factor
#'@examples
#'createFactor(sample(1:3, 10, TRUE), LETTERS[1:3])
createFactor <- function(x, levels) {
    .Call('activeH5_createFactor', PACKAGE = 'activeH5', x, levels)
}

#'@title Function to create file a h5 file
#'
#'@description Function to create a h5 file. It is intended for internal use only
#'
#'@param filePath a character denoting the path to the location where the h5 file will be written
#'@param overwrite integer 1 for overwrite and 0 for not overwrite. Will fail if overwrite is 0
#'@return int 0
h5CreateFile <- function(filePath, overwrite) {
    .Call('activeH5_h5CreateFile', PACKAGE = 'activeH5', filePath, overwrite)
}

#'@title Function creates the groups for the meta data to be written to the h5 file
#'
#'@description Function to create the groups in the h5 file before it is populated.
#'This function is intended for internal use only
#'
#'@param filePath character path to the location where the h5 file will be written
#'@return int 0
h5CreateMetaData <- function(filePath) {
    .Call('activeH5_h5CreateMetaData', PACKAGE = 'activeH5', filePath)
}

#'@title This function writes a character vector to the meta data
#'
#'@description This function writes a character vector to the meta data and is intended for internal use.
#'
#'@param charName the name that will be given to the meta data character vector
#'@param charVec the character vector to be written as meta data
#'@param filePath the path to the h5 file where the data will be written
#'@param update integer denoting whether the data item is new or whether it is an update 
#'(which will overwrite any previous item)
#'@return int 0
h5WriteCharVector <- function(charName, charVec, filePath, update) {
    .Call('activeH5_h5WriteCharVector', PACKAGE = 'activeH5', charName, charVec, filePath, update)
}

#'@title This function writes an integer meta data to file
#'
#'@description This function is inteded for internal use
#'
#'@param intName the name of the meta data item to be written
#'@param integer int that will be written to the meta data described by intName
#'@param filePath character path to the h5 file where data will be written
#'@param update int flag for whether item is new (0) or whether it will overwrite a previous item (1)
#'@return int 0
h5WriteInt <- function(intName, integer, filePath, update) {
    .Call('activeH5_h5WriteInt', PACKAGE = 'activeH5', intName, integer, filePath, update)
}

#'@title Function to write the levels of a factor variable to meta data
#'
#'@description Function is intended for internal use
#'
#'@param charName character denoting the meta data name of the factor to be written
#'@param charVec characer denoting the factor levels to be written
#'@param filePath character denoting the location of the h5 file
#'@param update int flag for whether item is new (0) or whether it will overwrite a previous item (1)
#'@return int 0
h5WriteFactor <- function(charName, charVec, filePath, update) {
    .Call('activeH5_h5WriteFactor', PACKAGE = 'activeH5', charName, charVec, filePath, update)
}

#'@title Function to write a matrix chunk to file
#'
#'@description Function is intended for internal use
#'
#'@param dset character denoting the meta data name of the data set
#'@param chunk matrix that will be written to h5file
#'@param dim numeric containing the dimension of the matrix that will be written to file
#'@param filePath character denoting the location of the h5 file
#'@return int 0
h5WriteDoubleMat <- function(dset, chunk, dim, filePath) {
    .Call('activeH5_h5WriteDoubleMat', PACKAGE = 'activeH5', dset, chunk, dim, filePath)
}

#'@title Function to finalize h5 file contents allowing them to be read by another user
#'
#'@description The same as the h5CloseFile() function
#'
#'@param filePath character path to the file which will be flushed
#'@return int 0
h5FlushFile <- function(filePath) {
    .Call('activeH5_h5FlushFile', PACKAGE = 'activeH5', filePath)
}

#'@title Function to close the h5 file
#'
#'@description Closes the h5 file
#'
#'@param filePath character path to the file which will be flushed
#'@return int 0
h5CloseFile <- function(filePath) {
    .Call('activeH5_h5CloseFile', PACKAGE = 'activeH5', filePath)
}

#'@title Function to read a character vector from meta data
#'
#'@param charName character the name of the meta data item to be read back from file
#'@param filePath character for the path to the file where the item will be read
#'@return character containing the character vector that has been read from meta data
h5ReadCharVector <- function(charName, filePath) {
    .Call('activeH5_h5ReadCharVector', PACKAGE = 'activeH5', charName, filePath)
}

#'@title Function to read factor levels from meta data for a pgiven factor
#'
#'@param charName character denoting the factor from the meta data factor
#'@param filePath character denoting the path to the h5 file
#'@return character of factor levels
h5ReadFactor <- function(charName, filePath) {
    .Call('activeH5_h5ReadFactor', PACKAGE = 'activeH5', charName, filePath)
}

#'@title Function to read an integer item from meta data
#'
#'@param intName character for the name of the item to be read back
#'@param filePath character for the path to the h5 file
#'@return int iteger item defined by intName in the meta data
h5ReadInt <- function(intName, filePath) {
    .Call('activeH5_h5ReadInt', PACKAGE = 'activeH5', intName, filePath)
}

#'@title Function to read a matrix chunk from a h5 file
#' 
#'@param chunkName the name of the chunk to be read back
#'@param filePath the path to the h5 file
#'@return matrix chunk defined by chunkName
h5ReadDoubleMat <- function(chunkName, filePath) {
    .Call('activeH5_h5ReadDoubleMat', PACKAGE = 'activeH5', chunkName, filePath)
}

#'@title Function for dummy read
#' 
#'@param chunkName the name of the chunk to be read back
#'@param filePath the path to the h5 file
#'@return int 0
h5DummyRead <- function(chunkName, filePath) {
    .Call('activeH5_h5DummyRead', PACKAGE = 'activeH5', chunkName, filePath)
}

#' @title Fast model frame for activeReg
#' 
#' @description Function returns a scaled down model frame essentially returning list with no NA values.
#' Each item in the list represents a column in the data frame.
#' 
#' @param chunkName character name of the chunk to be read
#' @param selCols character vector of columns to select
#' @param filePath character path to file where chunk is to be read from
#' @return list representing a data frame with no NA values.
h5ModelFrame <- function(chunkName, selCols_, filePath) {
    .Call('activeH5_h5ModelFrame', PACKAGE = 'activeH5', chunkName, selCols_, filePath)
}

#'@title Function returns a data frame chunk as a list object to R where the final cbind will take place 
#'
#'@param chunkName the name of the chunk to be read
#'@param filePath the path to the h5 file
#'@return List representing chunk data frame
h5ChunkList <- function(chunkName, filePath) {
    .Call('activeH5_h5ChunkList', PACKAGE = 'activeH5', chunkName, filePath)
}

#'@title Function returns a column subset of data frame chunk as a list
#'
#'@param chunkName the name of the chunk to be read
#'@param selCols the columns that will be selected
#'@param filePath the path to the h5 file
#'@return List representing chunk data frame
h5ChunkSel <- function(chunkName, selCols, filePath) {
    .Call('activeH5_h5ChunkSel', PACKAGE = 'activeH5', chunkName, selCols, filePath)
}

#'@title Legacy function to return a data frame chunk as a list
#'
#'@description Experimental function not intended for use at all
#'
#'@param chunkName the name of the chunk to be read
#'@param filePath the path to the h5 file
#'@return List of the data frame chunk
h5ReadDoubleMat2 <- function(chunkName, filePath) {
    .Call('activeH5_h5ReadDoubleMat2', PACKAGE = 'activeH5', chunkName, filePath)
}

#'@title Legacy function to return a data frame chunk as a list
#'
#'@description Experimental function not intended for use at all
#'
#'@param chunkName the name of the chunk to be read
#'@param filePath the path to the h5 file
#'@return List of the data frame chunk
h5ReadDoubleMat3 <- function(chunkName, filePath) {
    .Call('activeH5_h5ReadDoubleMat3', PACKAGE = 'activeH5', chunkName, filePath)
}

#'@title Function to write a matrix to memory and return a pointer
#'
#'@description Intended for internal use only
#'
#'@param obj matrix to be written to memory
#'@return externalptr 
h5WriteMemMAT <- function(obj) {
    .Call('activeH5_h5WriteMemMAT', PACKAGE = 'activeH5', obj)
}

#'@title Function to write a data frame object to memory and return a pointer
#'
#'@description Intended for internal use only
#'
#'@param obj data frame to be written to memory
#'@return externalptr 
h5WriteMemDF <- function(obj) {
    .Call('activeH5_h5WriteMemDF', PACKAGE = 'activeH5', obj)
}

#'@title Function to read a matrix from memory when given the external pointer
#'
#'@description Intended for internal use only
#'
#'@param ptr an externalptr to the matrix object to be retrieved
#'@return matrix that is held at the externalptr
h5ReadMemMAT <- function(ptr) {
    .Call('activeH5_h5ReadMemMAT', PACKAGE = 'activeH5', ptr)
}

#'@title Function to read a data frame that has been stored in memory when given the external pointer
#'
#'@param ptr externalptr to data frame stored in memory
#'@return the data frame that is helpd at the externalptr
h5ReadMemDF <- function(ptr) {
    .Call('activeH5_h5ReadMemDF', PACKAGE = 'activeH5', ptr)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('activeH5_RcppExport_registerCCallable', PACKAGE = 'activeH5')
})
